M48
; DRILL file KiCad 10.0.5 date 2026-07-29T19:35:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-29T19:35:35-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X216.536Y-92.826
X223.536Y-92.826
T2
X73.66Y-91.44
X185.42Y-91.44
M30
